### ISSUE TITLE
Streams have been just randomly turning off the past 2 days

### ISSUE THREAD

**Issue by davidpuetter** [anxdpanic/plugin.video.twitch#102]
Hey, 
I'm using 1.1.8 of the Addon and the latest OpenELEC update for my Raspberry Pi B. Since Friday, I've been unable to fluidly watch a stream, because they just turn off at random points and return me to the following list. Sometimes I can watch for 30 seconds, and sometimes for 5 minutes. I've tried various streams available with them all having the same errors.
I've uploaded a section of my xbmc.log here: http://pastebin.com/qjan3UqR
I also tried with the 1.1.0 release on the official addons list that comes with XBMC, with it having the same error.

**Comment by MrSprigster** [comment]
Hello @davidpox,

Firstly, please disregard any older versions of the Addon as Twitch recently updated their API which rendered all versions earlier than 1.1.8 useless. 

Secondly (and unfortunately), this Addon doesn't handle any of the playback of streams, it simply passes a URL to the XBMC/Kodi player which handles everything else. This means that the issues you are experiencing are not caused by anything we are able to change and therefore in this case we are unable to help solve the problem for you.

My first instinct would be to check your connection to Twitch servers as those random drop outs you describe point towards a likelihood of network related issues. If you have access to a VPN it's worth a try watching via that to rule out ISP routing issues to Twitch servers (which are fairly common.. I've experienced them first hand and now use a VPN from privateinterneraccess.com which solved my problem completely).

Good Luck!

Sprig

**Comment by davidpuetter** [comment]
My connection to Twitch works perfectly fine on Computer and my Tablet, I'm able to watch streams on any quality without dropping. With my Raspberry Pi, I have tried reinstalling the operating system (OpenELEC) and installing a different OS (RaspBMC) with no success. 
Also, I have no access to a VPN or proxy

**Comment by ingwinlu** [comment]
As mr sprig already mentioned, this plugin only handles urlresolving. If
the connection drops, we can't do anything about it
Am 21.12.2014 17:13 schrieb "davidpox" notifications@github.com:

**Comment by MrSprigster** [comment]
Worth a try to install of XBMC/Kodi with the Twitch add-on on your Windows PC to isolate the problem to the Raspberry Pi.. if you get the same issue on Windows, I'd put money on it being network/internet related. I can guarantee your problem is not caused by the operation of this add-on if that helps.

Sprig
