### ISSUE TITLE
Twitch now requires oauth tokens.

### ISSUE THREAD

**Issue by shadowofdarkness** [anxdpanic/plugin.video.twitch#186]
People can get the tokens here http://www.twitchapps.com/tmi/
This add-on is broken until updated to support these and just gives http errors.

**Comment by kokarn** [comment]
This is actually already included (since https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/commit/65e9a98ad383cd9682671e5f57d99893a0c11714) which is published as version 1.4.1. 
What version are you on?

**Comment by Giacom** [comment]
Yeah, there was a warning about this a few months ago. 

If you cannot update due to dependencies, I was on RaspBMC, which was no longer being supported, so I had to re-image my Raspberry Pi to OSMC to get the latest version of Kodi for the Raspberry Pi. This would then let me install the latest version of the add-on.

**Comment by Mastasly** [comment]
Well it might b included...but im on newest 1.4.1 app and after oAuth introducing by twitch application stopped working
Like first commented said it give HTML error now..

**Comment by MrSprigster** [comment]
Use the current version on github and your problems will magically
disappear :). I need to push this version to the kodi official repository.

**Comment by shadowofdarkness** [comment]
I just got home and my Kodi install found a update to the Twitch add-on so everything works now.
