### ISSUE TITLE
Playback failed Raspberry PI updated  Librtmp

### ISSUE THREAD

**Issue by Riftcore** [anxdpanic/plugin.video.twitch#20]
Sometimes I get playback failed on the PI random times, I would say its 90% of the time.

I am very lucky if I get a steam to run. (I normal have to keep trying it over and over and even than it might now work in the end)

Here is the log

http://pastebin.com/91P04fsi

Any ideas? as it's safe to say this addon gets a hammering in are home.

Cheers

**Comment by thaweed** [comment]
Use this Version https://skin-git.googlecode.com/files/plugin.video.twitch.zip
From here: http://forum.xbmc.org/showthread.php?tid=134538&page=13

**Comment by Riftcore** [comment]
Still getting the same problem

**Comment by ccaspers** [comment]
Hey, does the problem still exist with the current version?

**Comment by thaweed** [comment]
I dont habe thi

**Comment by ccaspers** [comment]
You mean "I don't have it" ? ^^

**Comment by thaweed** [comment]
Sorry, my phone messed up on my last comment somehow.
What i was trying to say:
Dont have this issue anymore with the latest of Twitch.tv Plugin version on my Linux(Debian)/Windows(Win7)/Raspberry(raspbian/raspbmc) system but still have it on my Android(4.1.2 Cyanogenmod).

**Comment by ccaspers** [comment]
Same version of the Plugin? Or older version? If the plugins version is the same on both devices it might have to do with xbmc rather than the twitchplugin. Can you provide a log?

**Comment by thaweed** [comment]
Ok i fixed it on my android device aswell, it was an old librtmp causing this behaviour.
Even though i changed the librtmp already 100% it got overwritten with the stock librtmp somehow.

I think this issue is not plugin related and should be closed unless we get some kind of proof from Xencored that the plugin is responsible. Xencored get in touch with me if you want and i will help you to figure it out. I guess you put the librtmp in the wrong spot on your raspberry or something like this.

Thanks everybody.

**Comment by Riftcore** [comment]
Howdy, I don't use a Raspberry Pi anymore (got sick of waiting for the slow arse menus)

Sorry!

**Comment by ccaspers** [comment]
Thanks for closing :)
