### ISSUE TITLE
suggestions: reconnect, blacklist

### ISSUE THREAD

**Issue by ghost** [anxdpanic/plugin.video.twitch#213]
- the plugin could monitor the player and eventually restart the stream in case of playback interruptions
- it could manages a list of hidden games/channels

**Comment by ghost** [comment]
[this link](https://openuserjs.org/scripts/LinogeFly/Hide_unwanted_streams_on_Twitch) browser implementation of the hide feature

**Comment by anxdpanic** [comment]
@untoreh blacklisting has been added for #235 if you're interested in testing/providing feedback.

**Comment by ghost** [comment]
thanks for adding the feature.
- the confirmation dialog seems annoying since its easy to undo an entry from the addon settings
- games/subjects and channels are not crossreferenced. If you blacklist a game from the game list and you browse the channels list, channels with that game should be hidden

**Comment by anxdpanic** [comment]
Thanks for the feedback 👍 

For confirmation I will see about adding a toggle to Blacklists settings, as accidental clicks could be frustrating as well. added in #252
Cross-referencing is on the todo, have to implement cursor/index shifting so empty next page lists and stuff don't happen.

**Comment by anxdpanic** [comment]
#255 added cross referencing where possible, search is the only thing left unfiltered

**Comment by ghost** [comment]
there appears to be duplicated entries probably caused by pagination

**Comment by anxdpanic** [comment]
thanks, should be resolved in alpha11

**Comment by NuisMons** [comment]
Really BIG thanks for blacklist feature!

**Comment by anxdpanic** [comment]
reconnect added in #263 for V2 (#235)

**Comment by ghost** [comment]
do you think it would be useful an option to black list a game directly from the channels list ?

**Comment by anxdpanic** [comment]
I added games to any video content listing now

**Comment by ghost** [comment]
I think there is still an issue with duplicates, when you blacklist an entry and the list gets reloaded, if a new page is fetched the first/last item appears twice. 
Also I have experienced another problem although I am not sure what is the cause and it is somewhat rare, basically the list stops loading items and a few of them disappear, it might be related to the duplicate bugs messing about id lists, clearing the cache (reset function cache) fixes it

One last filter option might be a keyword filtering for example excluding streams having "rebroadcast/rerun" in the title

**Comment by anxdpanic** [comment]
I likely won't get a chance to sit down to it until later tomorrow here. (EST) The offsets may be off by 1, could have swore I double checked that. The second issue is likely between our cache/twitch's cache and max requests limit. If we're going from offset 10-20, their list may have shifted due to cache time and sorting method, it's possible we may get half or more of the same results from 0-10 if those results shifted in their sorting. Scale that with a large blacklist and the amount of requests required keeps increasing, it's a matter of finding a suitable balance for us and non-abusive api usage.

I've only seen rebroadcast/reruns titles in playlists, is this being done with live/vods as well? I can look into this for future versions. At this point want to get us stable and released with the current feature set.

**Comment by anxdpanic** [comment]
Haven't been able to reproduce either, though I increased the limit per request so this should lessen the chances of this happening. Will look to make improvements in this area in future updates.

**Comment by ghost** [comment]
maybe you can try with my list which is kind of fat already [link](https://pastebin.com/raw/TuAi6wdE)
for examples on rebroadcasts channels all esl channels run 24/7 when not airing live

**Comment by anxdpanic** [comment]
Was still unable to reproduce, may be due to the changes I had made just prior. Opened #284 to be addressed in a future minor update. Thank you for testing and feedback 👍 

Closed by #282
