### ISSUE TITLE
Stream Options (high, medium, low etc)

### ISSUE THREAD

**Issue by WilliamStam** [anxdpanic/plugin.video.twitch#225]
so looks like if you set a stream quality (1080 at 60 etc) it doesnt work as well as for instance "high". using livestreamer my rpi2 and rpi3 can play the streams MUCH better than using the plugin. im assuming its cause the plugin tries to force a set size and the stream only supports xyz?

[cli][info] Found matching plugin twitch for URL xxxxxxxx
[plugin.twitch][info] Attempting to authenticate using OAuth token
[plugin.twitch][info] Successfully logged in as xxxxxxxxx
[cli][info] Available streams: audio, high, low, medium, mobile (worst), source (best)

could the plugin do the same? return the available stream qualities? most of the streams i tested use the high, low, medium options. none have had the 1080, 720 etc

**Comment by WilliamStam** [comment]
editing the py files doesnt help.. guessing it uses the compiled pyo files to work :( and i dont have a setup for it.

**Comment by JoaquinsVoid** [comment]
Well, something is off with the matching. Setting 1080p30 in the settings results in 1080p60, even though the stream is available as 1080p30 under the label High. I've been struggling with this myself because p60 twitch streams always seems to have audio drifting on my pi3.

I guess the cleanest solution would be to have a setting for "Always ask" when you start a stream and just present the qualities actually available. 

(As for the pyo-files you can just delete them and a new one will be created, provided there are no bugs in the code. Spaces, not tabs. ;D )

**Comment by cesarDevOp** [comment]
Hello,
i having the same issue. I try to change the quality, but it allways runs on 1080.
I try before playing and in addon configuration (420p30, 720p30, 720p60...), but nothing changes.

**Comment by cesarDevOp** [comment]
@anxdpanic Now I can change quality videos. Thanks for your work.

I caught all python code and I replaced on my rasp addon folder, because I tried to create something like "plugin.video.twitch-1.4.6~alpha2.zip" but kodi warns on its structure

Tell me ff you need any help

**Comment by anxdpanic** [comment]
@cesarDevOp Thanks Good to hear 👍  I zipped it up now. https://raw.githubusercontent.com/anxdpanic/__testing_repository/master/zips/plugin.video.twitch-1.4.6.alpha2.zip

@WilliamStam and @JoaquinsVoid if you're interested in testing/providing feedback, quality handling has been re-done for #235. Source or Always ask, with ability to set default stream/video/clip qualities per channel to override.

**Comment by anxdpanic** [comment]
Closed by #282
