### ISSUE TITLE
Unable to view twitch prime subbed stream.

### ISSUE THREAD

**Issue by malucious81** [anxdpanic/plugin.video.twitch#230]
I am new to github. I apologize if this is not the proper way to post a bug.  I am having issues viewing a stream in particular on both my Linux desktop (Fedora 25, Kodi 17.0 Twitch app. ver 1.4.5) and my Raspberry PI3 running Openelec 6.0.3 (Kodi ver 15.2 also 1.4.5 of the addon).

I never had issues before viewing this stream but lately I get the "No Live Data" found error when trying to watch live. I cannot think of any recent changes, beside me Twitch Prime subbing to the channel. I tried putting in a new OAUTH key but the stream still fails. I attached the log file containing the error near the bottom. Any help would be appreciated.

[kodi.zip](https://github.com/MrSprigster/Twitch-on-Kodi/files/840099/kodi.zip)

**Comment by anxdpanic** [comment]
This is likely regarding #231, will see if I can get a fix in soon

**Comment by anxdpanic** [comment]
#234 should resolve this

**Comment by judson-w** [comment]
Hello, I am also new to github but I had the identical issue as malucious81, and I want to clarify a little bit.

The issue is that the stream we have Twitch Prime subbed to (which, incidentally is the same channel, AnneMunition) does not work, but all other streams do (at least, for me they do).

I went ahead and applied the resolution from #234 but now every stream fails to load.  I have attached the Debug Log from attempting to access the problem stream and a stream that previously had no issue.

I admit I am new to python, but I wonder if part of the issue may come from the edits of line 202 of api.py:

if ('p30"' not in data) and ('p60"' not in data):

It seems that a " is missing in both parenthesis, as when I was editing the file, it highlighted 'p30"' not in data) and ('p60"' rather than just 'p30"' and p60'".  

I do thank you for your help in this matter.

[kodi.txt](https://github.com/MrSprigster/Twitch-on-Kodi/files/849520/kodi.txt)

**Comment by judson-w** [comment]
A new bit of info, I was watching the stream in a browser on another laptop, and AnneMunition stated she was streaming on the new transcode stack that twitch was testing.  It is likely that this was the issue and not the pure coincidence that both malucious81 and I both subbed using twitch prime.  Thus, I would say that this issue is identical #231.  

However, my previous issue with the solution provided still stands.

**Comment by malucious81** [comment]
New transcode stack? Interesting. I updated the add-on on my desktop and I am able to stream the channel. I have not gotten it to work on my Pi3 running Openelec. Edit. I want to say thank you for the help :)

**Comment by judson-w** [comment]
That is the term she used.  Verbiage seems close enough to what #231 talks about.  I am also running Openelec 6.0.3 so that may be where the issue is,  Tomorrow I will double check that I made the edits correctly.

Thanks again for your help on this.  I am trying to learn things as quickly as I can.

**Comment by anxdpanic** [comment]
Yea I was able to check when she was live, it is definitely related to qualities/transcode stack. With 'p30"' and 'p60"' the quotations are correct. I've zipped up the current with an alpha bump so it should install over the old one for you no problem. [1.4.6~alpha1.zip](https://github.com/anxdpanic/__testing_repository/blob/master/zips/plugin.video.twitch-1.4.6~alpha1.zip?raw=true)

**Comment by judson-w** [comment]
I just installed it over the old one and it works!  I can access that channel and others.  While the stream does lag occasionally, I am willing to chalk that up to hardware/connection issues.

Edit: I have hooked the htpc up to the tv and have been streaming for half an hour now without lag or freezing, so I think it is safe to say this works.

**Comment by malucious81** [comment]
That version worked for me too. Thanks again!

**Comment by anxdpanic** [comment]
Happy to hear!  👍 Thank you for confirming.
