### ISSUE TITLE
Streams are only playing in 'Source' quality 

### ISSUE THREAD

**Issue by Giacom** [anxdpanic/plugin.video.twitch#241]
I'm having an issue where, no matter what quality I put in the settings, it will play the stream in source quality.  This is a big issue since my Pi can't handle it and will constantly lag. 

Version 1.4.5

**Comment by Giacom** [comment]
Misdiagnosed the issue; seems to be an issue with my Pi.

**Comment by M3yo** [comment]
Actually I've got the exact same problem. No matter which quality I choose, it will play in source, which seems to be too much for my PI2.

@Giacom Did you solved this issue by yourself ?

**Comment by Giacom** [comment]
Yes I did and I have a Pi 2 as well.

The issue was that I was using an Ethernet cable before for my Pi for access to the internet. I had to then move it to an area with no Ethernet cable available so I used a spare WiFi dongle (advertised for Raspberry Pis).

My theory was that the WiFi dongle wasn't getting enough power.  I then tested it with and without an Ethernet cable and that definitely is what caused the issue. This meant I would have to get a powered USB hub to plug it into so that it would get enough.

Instead of doing that though I just decided to get a Raspberry Pi 3, with built in WiFi, and now it works flawlessly.

**Comment by M3yo** [comment]
I always use a ethernet cable, so I doubt it's the issue, because it seems pretty straigth forward:

I watch AdmiralBulldog (twitch channel), a few days ago he upgraded his stream quality from 1600*900@60fps [(eg here)](https://www.twitch.tv/videos/131966616) to 1920*1080@60fps [(here)](https://www.twitch.tv/videos/133761213)

Since, VODs (and live) are unwatchable, so I went on internet and  try to find how to fix, I tried to tweak the hardware acceleration playback thing : 
With mmal (default), the video is very laggy, clearly something is wrong.
With omxplayer, the video is fine, but the audio is getting delayed -> the delay is noticeable after a few seconds, the audio keep delaying until stream crashes eventually.

So a temporary solution would be to play in lower quality, which doesn't seem to work.

@Giacom can you eventually try to watch the last VOD of the streamer and tell me if it works flawlessly on your pi3 ? (so I don't waste my monney on a PI3 :D)

**Comment by Giacom** [comment]
Sure I'll give it a try after work.  I'll be using OSMC with default config settings.

**Comment by Giacom** [comment]
I forgot to mention that while I was looking into this issue, the streams stopped only being played in Source quality. It would still lag when playing for my Pi 2 /w WiFi dongle though.

**Comment by Giacom** [comment]
@M3yo Ok just tested it. The Pi 3 can't handle your VOD at source quality though I was able to change the settings to 720p60fps and it was playing just fine.

**Comment by M3yo** [comment]
Ok thanks for the update @Giacom, I really appreciate 👍 

Problem is, when I change quality, it stills play it at source quality, and it lags as hell :/

I'm gonna wait a bit for a fix, thanks anyway dude.

**Comment by M3yo** [comment]
Hey, @Giacom I solved the lag issue !

I started by updating my kodi (17.1 iirc), problem was still here. Then I tweaked the cache settings, carefull though parameters have changed in v17 so update your advancedsettings.xml, here's the settings that I've used, I can now read 1080p60hz streams fine 👍 

```
<advancedsettings>
  <cache>
    <buffermode>1</buffermode>
    <memorysize>139460608</memorysize>
    <readfactor>20</readfactor>
  </cache>
</advancedsettings>
```
