### ISSUE TITLE
jsonrpc doesn't work anymore

### ISSUE THREAD

**Issue by Alexandar-Dev** [anxdpanic/plugin.video.twitch#302]
This doesn't work anymore:
`<jsonrpc>plugin://plugin.video.twitch/?mode=11/</jsonrpc>`
Can you help me? :(

**Comment by anxdpanic** [comment]
the params for playing;
videos are { mode: play, video_id: <video_id> }
streams are { mode: play, name: <channel_name>, channel_id: <channel_id> }
clips are { mode: play, slug: <clip_slug>, channel_id: <channel_id> }
optional parameter for playback are { ask: true, player: true }, ask will force asking for quality, and player will use Kodi Player() instead of setResolvedUrl which can be useful from certain contexts.

**Comment by anxdpanic** [comment]
additional info in #303
