### ISSUE TITLE
"unable to use the add-on at all"

### ISSUE THREAD

**Issue by StateOfTheArt89** [anxdpanic/plugin.video.twitch#34]
twitchadict wrote at xbmc.org (http://forum.xbmc.org/showthread.php?tid=134538&page=15)

> Since issue 32 of the twitch add-on has been fixed, I had was unable to use the add-on at all.
> 
> First of all, I am using raspbmc on the raspberry pi with an updated librtmp and can watch twitch streams via the twitch add-on from Middle. Unfortunately this add-on is not maintained and very unofficial.
> 
> I was unable to install the latest version of the official add-in from zip and thus update the version 1.0.0 from the repo with it. Even after uninstalling the v1.0.0 and installing the v1.0.1 zip from a pendrive, raspbmc showed the plugin as version 1.0.0. and the above issue was still there.
> 
> Since I wanted to check if the fix works for me, I did a complete reinstall of raspbmc from the recovery-function of my SD-Card. After encountering some problems with the add-on repo and updating librtmp again I could install the v1.0.1. 
> 
> As of now I get a user token error on every stream when using the new version. In the meantime I can always watch streams with the add-on from Middle. But only until some change on twitch breaks it.
> 
> Up until now i was planning on using the raspi with the above setup to show streams during some Barcraft events, but seeing how problematic this seems to be, I am open to suggestions.

I will test it myself asap...

**Comment by Mir4r** [comment]
I also have the "User Token error".
When I install the version that i get from the xbmc-repo, I can watch streams without a subscription option. When I use the files, with the "subscription-fix", I get the "User Token Error". This is only happening since today. On Sunday I was able to watch all streams.

**Comment by lordthumper** [comment]
Can confirm what Mir4r said.

Had to revert to 1.0.0.

**Comment by Mir4r** [comment]
I tried it again in the evening and it worked. I had a second Sd-Card, where I used the fix "35ac843" (s. https://github.com/StateOfTheArt89/Twitch.tv-on-XBMC/issues/32) and it worked fine then. When I wrote the last post I also tried it with this SD-Card an I had the Error... 
So I think its a twitch problem. No problem with the Addon

**Comment by ccaspers** [comment]
It probably has to do with the json supplied by twitch and the way we validate it. I would really like to dig deeper into it but I have no time to spare for the next two weeks, and it's the same for @stateoftheart89

If anyone is able to investigate what's going wrong within the resolver-class that would be great. I hope the issue doesn't upset you all too much for now :/

**Comment by roggerooster** [comment]
Since 2 days, the plugin doesn't work at all. "User token error" on all streams. I am using the twitch plugin 1.0.1 on my raspberry pi. So the changes and suggestions mentioned by "Mir4r" has already been applied in the code at twitch.py.

The following is listed in my xbmc.log:

10:32:47 T:2890036288  NOTICE: Thread Background Loader start, auto delete: false
10:32:50 T:2890036288  NOTICE: Thread XBPyThread start, auto delete: false
10:32:50 T:2890036288  NOTICE: -->Python Interpreter Initialized<--
10:32:53 T:2890036288  NOTICE: [xbmcswift2] Request for "/" matches rule for function "createMainListing"
10:32:53 T:2881647680  NOTICE: Thread Background Loader start, auto delete: false
10:32:55 T:2881647680  NOTICE: Thread XBPyThread start, auto delete: false
10:32:55 T:2881647680  NOTICE: -->Python Interpreter Initialized<--
10:32:57 T:2881647680  NOTICE: [xbmcswift2] Request for "/createListOfGames/0/" matches rule for function "createListOfGames"
10:33:00 T:2890036288  NOTICE: Thread Background Loader start, auto delete: false
10:33:05 T:2890036288  NOTICE: Thread XBPyThread start, auto delete: false
10:33:06 T:2890036288  NOTICE: -->Python Interpreter Initialized<--
10:33:07 T:2890036288  NOTICE: [xbmcswift2] Request for "/createListForGame/StarCraft+II%3A+Heart+of+the+Swarm/0/" matches rule for function "createListForGame"
10:33:09 T:2890036288 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
10:33:10 T:2881647680 WARNING: Previous line repeats 19 times.
10:33:10 T:2881647680  NOTICE: Thread Background Loader start, auto delete: false
10:33:14 T:2881647680  NOTICE: Thread Jobworker start, auto delete: true
10:33:16 T:2890036288  NOTICE: Thread XBPyThread start, auto delete: false
10:33:16 T:2890036288  NOTICE: -->Python Interpreter Initialized<--
10:33:17 T:2890036288  NOTICE: [xbmcswift2] Request for "/playLive/weedamins/" matches rule for function "playLive"
10:33:17 T:2890036288 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
10:33:19 T:3037679616   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/weedamins/]
10:33:19 T:2775569472  NOTICE: Thread Background Loader start, auto delete: false
10:34:18 T:3037679616  NOTICE: Samba is idle. Closing the remaining connections

Hope that someone can spare some time and try to fix this issue! I am not able due to my pathetic knowledge about coding

**Comment by roggerooster** [comment]
Must be something else which is messing with us since I applied your changes in the code, the twitch-plugin is now not complaining about unicode errors. But just saying that the streams are unplayable. Within the game "Starcraft II", all the streams are unavailable for me since 1-2 weeks. Will paste in the log below what xbmc.log now returns:

12:15:00 T:2794075200  NOTICE: Thread Background Loader start, auto delete: false
12:15:04 T:2794075200  NOTICE: Thread XBPyThread start, auto delete: false
12:15:04 T:2794075200  NOTICE: -->Python Interpreter Initialized<--
12:15:06 T:2794075200  NOTICE: [xbmcswift2] Request for "/playLive/weedamins/" matches rule for function "playLive"
12:15:07 T:3038191616   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/weedamins/]
12:15:07 T:2890572864  NOTICE: Thread Background Loader start, auto delete: false
12:15:17 T:2890572864  NOTICE: Thread XBPyThread start, auto delete: false
12:15:17 T:2890572864  NOTICE: -->Python Interpreter Initialized<--
12:15:18 T:2890572864  NOTICE: [xbmcswift2] Request for "/playLive/wayne379/" matches rule for function "playLive"
12:15:20 T:3038191616   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/wayne379/]
12:15:20 T:2794075200  NOTICE: Thread Background Loader start, auto delete: false
12:15:28 T:2794075200  NOTICE: Thread XBPyThread start, auto delete: false
12:15:28 T:2794075200  NOTICE: -->Python Interpreter Initialized<--
12:15:29 T:2794075200  NOTICE: [xbmcswift2] Request for "/playLive/empiretvzerg/" matches rule for function "playLive"
12:15:31 T:3038191616   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/playLive/empiretvzerg/]
12:15:33 T:2794075200  NOTICE: Thread Background Loader start, auto delete: false
12:17:40 T:2768884800  NOTICE: Previous line repeats 1 times.

**Comment by KlingOne** [comment]
Yeah, noticed that too.
Seemed to be a strange coincidence that the 2 streams i tried after making the change worked.
But now nothing is working for me again either.
