### ISSUE TITLE
401 missing required oauth scope cant watch vods

### ISSUE THREAD

**Issue by BeatZeps** [anxdpanic/plugin.video.twitch#371]
Im logged in with my oauth token i can see all my subscriptions and can watch there live streams.
but if i try to watch vods i get this message:

Unauthorized
[401] missing required oauth scope.

**Comment by anxdpanic** [comment]
Can you post a [debug log](https://kodi.wiki/view/Log_file), I'm unable to reproduce

**Comment by BeatZeps** [comment]
I only get this error on the Amazon FireTV on my Phone and Laptop it works perfect.
I will post the log if i can get it tried it with adbLink but my temp folder seems to be always empty.

**Comment by anxdpanic** [comment]
@BeatZeps I ran into this issue when working on the latest update, it should be resolved now. Would you be able to try out https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.3.0-beta and confirm if the issue is resolved. Will need to install the script.module.python.twitch linked in the release before plugin.video.twitch.

**Comment by anxdpanic** [comment]
This should be resolved in v2.3.2 which was just accepted to the official repository. If this is still an issue please reopen the issue.
