### ISSUE TITLE
close stream if it goes offline

### ISSUE THREAD

**Issue by eusi** [anxdpanic/plugin.video.twitch#62]
Hey,

I don't know why, but my raspberry pi drives crazy if the stream is offline for a long time.

For example: I watch a stream a bit and close the TV then, but I didn't close the stream in xbmc. When the stream goes offline, your addon is forced to show the offline-screen of the stream. So far no problem. But if it shows the offline-screen for more than some hours my raspberry pi shows sooome heavy graphical bugs. As I mentioned,  I dont know why, maybe the gpu is too warm for a long time.

One possible solution is to close the stream like the youtube-addon. The youtube-addon closes the stream after it went offline. So this problem will not occur again.

greetings and thx for this great addon!
eusi

**Comment by MrSprigster** [comment]
I can't replicate this behaviour. For me, when a steam ends, the video stops and focus goes back to the previous menu I accessed. 

What settings are using (particularly quality) and which streamer were you watching when this behaviour occurred?

**Comment by MrSprigster** [comment]
I had a suspicion that twitch's re-encoder may have continued broadcasting the last image it received. However, I have tested with both 'Best possible' which is generally source and 720p re-encode and at the end of each stream, video stopped and I was returned to the menu. 

Is anyone else experiencing the same behaviour as @eusi? (if so, please provide as much detail as possible so that I am able to replicate).  

@eusi, just a thought... could it be the case that the streamer that you were watching continued to stream his/her own "stream offline" image?

**Comment by eusi** [comment]
I use default settigns, afaik. There were two different streamer, I could check later who they are, if u still need this information.

"For me, when a steam ends, the video stops and focus goes back to the previous menu I accessed."

Intereseting. I froze in " 'stream offline' image ". Your thought is right ;-) That might be the main issue?

**Comment by MrSprigster** [comment]
Yeah if it isn't too much trouble, the closer I get to replicating your environment,  the more likely it is that I will be able to work out why you are experiencing this issue. 

From the results of the testing that I've performed so far, the only logical assumption I can think of is that the streamer broadcasted their offline screen. This is however statistically unlikely to be the case for two separate consecutive streamers. 

I hate to say it but if I can't reproduce the issue,  I can't fix it so maybe your solution is to hit the stop button before turning off the TV (while I also take into consideration that this wouldn't be a solution in the case that you fall asleep watching a stream and rely on a sleep timer to turn off your TV).

Sprig

**Comment by eusi** [comment]
Hello again. 

Tonight, I was able to reproduce "your case" twice. 
I opened on my RPi-1 your addon and on my RPi-2 the youtube addon. I thought that there are probably differences after the stream is over...
Then I opend on both addons the LCS stream. I watched a bit and fall asleep while streaming. My TV turns off one hour later, but the both (!) streams were "frozen" on "offline-screen" after the stream ended.
After I turned on my TV at morning, both looks like this: http://www.youtube.com/watch?v=fbt-0LmQu5E
Heavy graphical bugs and CPU usage on constantly 90-100%. Have you any idea what the issue is for this?

**Comment by MrSprigster** [comment]
So this issue is presenting when using both the YouTube and Twitch addons. This  makes the XBMC video player itself the common denominator. 

I'm now thinking along the lines of the video player failing to stop due to no display being present (when the TV turns off, the hdmi disconnects and either leaves your raspberry pi with no display or switches to the low resolution av (yellow) port which may be causing the issue).  Are you able to enable debugging in XBMC and post a log after you encounter the issue again? 

Another thing to test is if a stream continues to play after it has finished while the TV is kept on. 

Sprig

**Comment by eusi** [comment]
Oh well, you are great ;-) Actually the graphical bugs occur after I turn off/on my TV. Is this a known "bug"? :-/

And yes, the stream continues fine.

xbmc.log while debugging (opened a twitch stream, then turned off tv, and turned on again 10sec later):
http://xbmclogs.com/show.php?id=130870

My workaround so far is to add in config.txt:
// Force HDMI even if unplugged or powered off
**hdmi_force_hotplug=1**

Do you know another solution like a CEC-function like "When the TV is switched off" -> "Stop video player"? :-/

**Comment by MrSprigster** [comment]
I'm not part of the XBMC development team so I'm not familiar with bugs in their player.  It may be worth posting in their forums regarding the graphical  errors that you are encountering when HDMI is disconnected and reconnected . 

This is a good news bad news situation as far as I am concerned.  The good news: Your workaround is inspired and may help other people that experience similar issues (thanks for posting that).  The bad news: This issue falls outside of the scope of the development of this addon, meaning I am powerless to provide you with a solution.  

My advice is to research the HDMI issue on the XBMC and relevant Raspberry Pi Forums and if this issue isn't already known, you should report it to their development teams. I'm only guessing but similar problems to this one may actually be responsible for the existence of the config.txt option that you used in your workaround.

As this issue is not caused by the functionality of this addon, please feel free to mark the issue as closed. 

Addition:
With the config.txt option turned off you could write a simple python or bash script that checks the resolution once every 30 seconds and if it drops below 1920 \* 1080, kill the XBMC process and then reload it when the resolution returns. However I would recommend just sticking with your workaround if there are no negative side effects. 

Thanks, 

Sprig

**Comment by eusi** [comment]
Sprig, thanks for your great and very fast support! Good man!

I will also research and discuss this issue in openelec forum.

Cya friend!
