### ISSUE TITLE
Stream drops unexpectedly 

### ISSUE THREAD

**Issue by kokarn** [anxdpanic/plugin.video.twitch#63]
When watching a stream, it will stop for a second as to buffer and then stop the stream.

Most of the time i can start it again, no problem. But sometimes it just stays on buffering for a long long time without starting anything.

It feels like it tries to buffer, fails and then quits.

This problem only appears sometimes and quite randomly I'm afraid. However, I've had it happen for a long time, almost a year on and off.

Dedicated HTPC on a 100mbit line.

I'll try to get a log, kinda hard when it's so random.

**Comment by kokarn** [comment]
I managed a log!

http://xbmclogs.com/show.php?id=135688

Sorry about the insane size, it had been on for quite some time when i got it.

Around line 11650 is the good stuff.

**Comment by lwis** [comment]
I could be very wrong with this statement, but I've noticed Twitch has adopted a new ad delivery system on their website (forcing all viewers to drop and restart the stream every time an ad plays, regardless of adblocker).

I've not done any investigation myself, so I'm probably talking out of my ass.

**Comment by MrSprigster** [comment]
The first thing I'd recommend is to update your XBMC installation as the version you're using is almost a year old and if we're lucky, this may just fix the issue. I'm running a very similar htpc setup to yours except I'm using an up to date build of XBMC and I'm running smoothly on all streams. 

From your log it looks like the stream stopped because the player was expecting an audio packet which never arrived suggesting a network issue of some sort. You did have several network related lib errors at the beginning of the log file which an XBMC client update might fix. 

@iwis I don't think it's related to ads as I'm running fine without any issues and a forced stream disconnect for adverts would affect everyone. Plus we'd have a lot more complaints popping up on here if that was the case.

**Comment by kokarn** [comment]
Yeah let's hope for that.
I'll give it a shot and will keep you posted how it turns out.

Thanks for a quick reply!

**Comment by MrSprigster** [comment]
Nice one,  good luck with it. If the issue returns we can investigate further.  And no problem for the quick reply..  I quite enjoy helping people out :) 

Sprig

**Comment by kokarn** [comment]
So i've updated both the plugin and XBMC, didn't seem to change anything i'm afraid.

I can also add the information that it happens for both hq streams and lower res streams.

**Comment by MrSprigster** [comment]
Oh no, that is a shame. I'm thinking that this issue is individual to you, so we should try to find out what is disconnecting you from the stream.  

How is your network connected? Wired or Wireless?

If you have another computer in your house, try running the same setup on that and if you're still experiencing the same issues it may be related to your network hardware. 

It is worth mentioning that running P2P software that uses a high number of connections could cause the router to hiccup long enough for the stream to disconnect so it would be worth turning this kind of software off while testing. 

I had issues with buffering on a 120mb/12mb connection in  the UK on the Virgin Media network due to their bad routing to twitch servers and I now watch through a VPN.  So it's also worth trying a decent speed proxy server in the XBMC system options to eliminate network routing issues on your ISP's end. 

Also turn off any third party software firewalls while testing too. 

Let me know how you get on. 

Sprig

**Comment by Klueze** [comment]
Hi there,

i got the same problem.

i am using XBMC 12.3 'Frodo' and the plugin is up to date. for me this issue happens all the time. i can watch twitch for 30-120 seconds, then it will drop every time and i have to restart the stream.

i use a wired connection with 50mbits ethernet. it happens on all stream resolutions. my computer si running win 7

Help would be nice.

Klueze

edit: On the same computer its no problem to watch twitch for hours without lag if i use a browser like chrome or firefox.
edit2: i created a log file: http://xbmclogs.com/show.php?id=145989 i startet the stream 3 times, 3 times it stopped as you can see in the log

**Comment by MrSprigster** [comment]
Hi @Klueze 

Just to clarify before I continue; this is not an issue with this Addon, it is an issue that is presenting after the Addon has passed the stream information to the XBMC Player and no changes that we could make to our code would help with this problem.

I have however taken a look at both yours and @kokarn's Debug Logs and both contain the following lines immediately before the stream stops playing:

DEBUG: CDVDPlayerAudio:: Discontinuity......
WARNING: CDVDMessageQueue(video)::Get - asked for new data packet, with nothing available
WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available

I have limited knowledge of the player but this suggests either an audio desync which never recovers or more likely a network related problem.

The following are worth a try:

Update your network card, sound card and video card drivers.

Turn off 'Sync playback to display' (in Settings > Video > Playback) as this may be causing audio sync problems.

If you still have issues it is definitely worth posting your issue over at the XBMC forums and include a full debug log file as well as the description of your problem. The guys over there have a much better understanding of the built in video player in XBMC so they may be able to help further.

Good luck! :+1: 

Sprig

**Comment by Huartonsson** [comment]
hey,

got the exact same issue, can wach for 30-120 seconds, then the stream will drop. tested on a wireless connection with different systems and different versions of xbmc, happens ever since the tech swtich by twitch a few months back. fiddled with different router settings, but couldn't find a  solution, very annoying stuff :(

**Comment by MrSprigster** [comment]
Closing due to issue being outside of our control.

**Comment by cobrafast** [comment]
I have opened a ticket with Kodi in order to resolve this issue, as I am affected by it, too.

If anybody else has something to add there, please go ahead.
- http://trac.kodi.tv/ticket/16042
